### ISSUE TITLE
Why are there only 62 sdfSamples from the MOW preprocessed sdf data provided in the repo?

### ISSUE THREAD

**Issue by dqj5182** [JudyYe/ihoi#15]
Although the train and set set for MOW data each consists of 350 and 92 samples, the preprocessed sdf data shared in preprocessed.md only contains 62 sdfSamples for MOW dataset. Is there reason for it? or are they mistakenly not provided?

**Comment by JudyYe** [comment]
Hi dqj5182. Thank you for pointing this out. Indeed it looks like I've made a mistake that only part of the preprocessed SDFs are compressed. But since it's been 2 years, I did not save the preprocessed files locally. Could you please follow preprocessing [instructions](https://github.com/JudyYe/ihoi/blob/cb00927a29a5d392565a200eee3fd2de1eabd09b/docs/preprocess.md#create-your-own-cache-data) to get them? I've followed it myself to preprocess other datasets (e.g. HOI4D) and it works for me. 

Apologize for the inconvenience!
